export const localStyles = {
  tabBar: {
    display: 'flex',
    gap: '0',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--glass-bg-light)',
  },
  tabButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    padding: '7px 4px',
    border: 'none',
    borderBottom: '2px solid transparent',
    backgroundColor: 'transparent',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 600,
    transition: 'all 0.15s',
  },
  tabButtonActive: {
    color: 'var(--primary-color)',
    borderBottom: '2px solid var(--primary-color)',
    backgroundColor: 'var(--primary-faint)',
  },
  tabIcon: {
    fontSize: '11px',
  },
  tabBadge: {
    padding: '0 5px',
    borderRadius: '999px',
    backgroundColor: 'var(--neutral-faint)',
    color: 'var(--text-dark)',
    fontSize: '10px',
    fontWeight: 700,
    minWidth: '16px',
    textAlign: 'center',
  },
  tabContent: {
    overflow: 'visible',
  },
  completedCapsuleHost: {
    marginTop: '4px',
    marginBottom: '8px',
    display: 'flex',
    justifyContent: 'flex-start',
    animation: 'fadeIn 0.18s ease-out',
  },
  executionHud: {
    maxWidth: 'min(820px, 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '4px 0',
    borderRadius: '10px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    backdropFilter: 'none',
    WebkitBackdropFilter: 'none',
    boxShadow: 'none',
    cursor: 'pointer',
  },
  executionHudMain: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '4px 2px',
    borderRadius: '8px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
  },
  executionHudTitleRow: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  executionStatusMark: {
    height: '24px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: 0,
    borderRadius: '999px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    color: 'var(--success-color)',
    fontSize: '11px',
    fontWeight: 850,
    whiteSpace: 'nowrap',
  },
  executionSummaryText: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 700,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  executionSeparator: {
    color: 'var(--text-dark)',
    fontWeight: 600,
  },
  executionSummaryError: {
    color: 'var(--error-color)',
  },
  executionActionCluster: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '6px',
  },
  completedCapsuleDock: {
    maxWidth: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
    padding: '6px 0',
    borderRadius: '999px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    backdropFilter: 'none',
    WebkitBackdropFilter: 'none',
    boxShadow: 'none',
    cursor: 'pointer',
  },
  overviewCapsule: {
    minHeight: '28px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    maxWidth: '180px',
    padding: '0 2px',
    borderRadius: '999px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 750,
    boxShadow: 'none',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  overviewCapsuleSuccess: {
    color: 'var(--success-color)',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  capsuleDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: 'var(--success-color)',
    boxShadow: '0 0 0 3px var(--success-faint)',
    flexShrink: 0,
  },
  capsuleKicker: {
    color: 'var(--text-dark)',
    fontSize: '10px',
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  capsuleActionButton: {
    height: '28px',
    padding: '0 9px',
    borderRadius: '999px',
    border: '1px solid var(--glass-border)',
    backgroundColor: 'var(--glass-bg-light)',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 800,
  },
  capsuleDetailsButton: {
    height: '28px',
    padding: '0 10px',
    borderRadius: '999px',
    border: '1px solid var(--primary-border)',
    backgroundColor: 'var(--primary-soft)',
    color: 'var(--primary-color)',
    fontSize: '11px',
    fontWeight: 850,
  },
  compactCompletedHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minHeight: '38px',
    borderBottom: 'none',
    borderRadius: 0,
    justifyContent: 'flex-start',
  },
  compactProcessedText: {
    color: 'var(--text-color)',
    fontSize: '12px',
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  compactChangeSummary: {
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 700,
  },
  compactActionGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  compactChevron: {
    flexShrink: 0,
    color: 'var(--text-muted)',
    fontSize: '12px',
    fontWeight: 800,
  },

  lineDeltaGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    flexShrink: 0,
  },
  lineDeltaCompact: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    flexShrink: 0,
  },
  lineDeltaChip: {
    padding: '1px 5px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
  },
  lineDeltaAdd: {
    backgroundColor: 'var(--success-soft)',
    color: 'var(--success-color)',
  },
  lineDeltaDelete: {
    backgroundColor: 'var(--error-soft)',
    color: 'var(--error-color)',
  },
  planTaskSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '10px',
    borderRadius: '8px',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--surface-subtle)',
  },
  planTaskHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
  },
  planTaskTitle: {
    color: 'var(--text-color)',
    fontSize: '12px',
    fontWeight: 850,
  },
  planTaskProgress: {
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 750,
    whiteSpace: 'nowrap',
  },
  planStrategyRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  },
  planStrategyChip: {
    minHeight: '20px',
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0 7px',
    borderRadius: '999px',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--glass-bg-light)',
    color: 'var(--text-muted)',
    fontSize: '10px',
    fontWeight: 750,
  },
  planTaskList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  planPhaseGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    paddingTop: '5px',
    borderTop: '1px solid var(--border-subtle)',
  },
  planPhaseHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    color: 'var(--text-dark)',
    fontSize: '10px',
    fontWeight: 850,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  planTaskItem: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 8px',
    borderRadius: '6px',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--glass-bg-light)',
  },
  planTaskItemCompleted: {
    borderColor: 'var(--success-border)',
    backgroundColor: 'var(--success-faint)',
  },
  planTaskItemFailed: {
    borderColor: 'var(--error-border)',
    backgroundColor: 'var(--error-soft)',
  },
  planTaskItemRunning: {
    borderColor: 'var(--primary-border)',
    backgroundColor: 'var(--primary-faint)',
  },
  planTaskMark: {
    width: '18px',
    height: '18px',
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    backgroundColor: 'var(--neutral-faint)',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 900,
  },
  planTaskMarkCompleted: {
    backgroundColor: 'var(--success-soft)',
    color: 'var(--success-color)',
  },
  planTaskMarkFailed: {
    backgroundColor: 'var(--error-soft)',
    color: 'var(--error-color)',
  },
  planTaskMarkRunning: {
    backgroundColor: 'var(--primary-soft)',
    color: 'var(--primary-color)',
  },
  planTaskName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--text-color)',
    fontSize: '12px',
    fontWeight: 750,
  },
  planTaskDependency: {
    marginLeft: '6px',
    color: 'var(--text-dark)',
    fontSize: '10px',
    fontWeight: 750,
  },
  planTaskStatus: {
    flexShrink: 0,
    color: 'var(--text-muted)',
    fontSize: '10px',
    fontWeight: 800,
  },
  drawerBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 80,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  changeDrawer: {
    width: 'min(520px, 92vw)',
    height: '100vh',
    backgroundColor: 'var(--surface-color)',
    borderLeft: '1px solid var(--border-subtle)',
    boxShadow: '-18px 0 36px rgba(0, 0, 0, 0.22)',
    display: 'flex',
    flexDirection: 'column',
    color: 'var(--text-color)',
  },
  drawerHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '14px 16px',
    borderBottom: '1px solid var(--border-subtle)',
  },
  drawerTitle: {
    color: 'var(--text-color)',
    fontSize: '15px',
    fontWeight: 850,
  },
  drawerMeta: {
    marginTop: '5px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 700,
  },
  drawerCloseButton: {
    width: '28px',
    height: '28px',
    border: '1px solid var(--border-subtle)',
    borderRadius: '6px',
    backgroundColor: 'var(--glass-bg-light)',
    color: 'var(--text-dark)',
    cursor: 'pointer',
    fontSize: '18px',
    lineHeight: 1,
  },
  drawerFileList: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  drawerFileSection: {
    border: '1px solid var(--border-subtle)',
    borderRadius: '8px',
    backgroundColor: 'var(--surface-subtle)',
    overflow: 'hidden',
  },
  drawerFileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderBottom: '1px solid var(--border-subtle)',
  },
  drawerFilePath: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--text-color)',
    fontSize: '12px',
    fontWeight: 800,
  },
  drawerDiffPre: {
    margin: 0,
    padding: '8px 0',
    maxHeight: '420px',
    overflow: 'auto',
    backgroundColor: 'var(--glass-bg-light)',
    fontSize: '11px',
    lineHeight: 1.45,
  },
  drawerDiffLine: {
    display: 'block',
    padding: '0 10px',
    whiteSpace: 'pre',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace)',
  },
  diffLineAdd: {
    backgroundColor: 'var(--success-faint)',
    color: 'var(--success-color)',
  },
  diffLineDelete: {
    backgroundColor: 'var(--error-faint)',
    color: 'var(--error-color)',
  },
  diffLineMeta: {
    backgroundColor: 'var(--primary-faint)',
    color: 'var(--primary-color)',
    fontWeight: 800,
  },
  diffLineNeutral: {
    color: 'var(--text-muted)',
  },
  reasoningList: {
    padding: '8px 10px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  reasoningItem: {
    padding: '8px 9px',
    borderRadius: '6px',
    border: '1px solid var(--info-border)',
    backgroundColor: 'var(--info-faint)',
  },
  reasoningHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    marginBottom: '4px',
  },
  reasoningTitle: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--text-color)',
    fontSize: '11px',
    fontWeight: 800,
  },
  reasoningTime: {
    flexShrink: 0,
    color: 'var(--text-muted)',
    fontSize: '10px',
    fontWeight: 600,
  },
  reasoningText: {
    color: 'var(--text-dark)',
    fontSize: '11px',
    lineHeight: 1.55,
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    wordBreak: 'break-word',
  },

  // 文件 Tab
  fileListHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 10px',
    borderBottom: '1px solid var(--border-subtle)',
  },
  fileListCount: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontWeight: 600,
  },
  fileFilterGroup: {
    display: 'flex',
    gap: '4px',
  },
  fileList: {
    padding: '6px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    maxHeight: '300px',
    overflowY: 'auto',
  },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    minHeight: '28px',
    padding: '2px 8px',
    borderRadius: '6px',
    backgroundColor: 'var(--surface-subtle)',
  },
  fileItemButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    minHeight: '28px',
    padding: '2px 8px',
    borderRadius: '6px',
    border: 'none',
    backgroundColor: 'var(--surface-subtle)',
    color: 'inherit',
    cursor: 'pointer',
    textAlign: 'left',
  },
  fileTypeIcon: {
    width: '18px',
    height: '18px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 800,
    flexShrink: 0,
    borderRadius: '3px',
    backgroundColor: 'var(--neutral-faint)',
    color: 'var(--text-muted)',
  },
  filePath: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'var(--text-color)',
    fontSize: '12px',
    fontWeight: 600,
  },
  fileStatusChip: {
    flexShrink: 0,
    fontSize: '11px',
    fontWeight: 800,
  },
  fileTime: {
    flexShrink: 0,
    fontSize: '10px',
    color: 'var(--text-dark)',
  },
  fileDiffToggle: {
    flexShrink: 0,
    color: 'var(--text-dark)',
    fontSize: '11px',
  },
  fileDiffPanel: {
    margin: '4px 0 4px 26px',
    borderRadius: '6px',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--glass-bg-light)',
    overflow: 'hidden',
  },
  fileDiffPre: {
    margin: 0,
    padding: '8px',
    maxHeight: '260px',
    overflow: 'auto',
    whiteSpace: 'pre',
    fontSize: '11px',
    lineHeight: 1.45,
    color: 'var(--text-muted)',
  },
  fileDiffEmpty: {
    padding: '8px',
    color: 'var(--text-dark)',
    fontSize: '11px',
  },

  // 活动 Tab：顶部栏 + 视图切换
  activityTopBar: {
    padding: '6px 10px',
    borderBottom: '1px solid var(--border-subtle)',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  activityReasoningToggle: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 8px',
    border: '1px solid var(--info-border)',
    borderRadius: '5px',
    backgroundColor: 'var(--info-faint)',
    color: 'var(--text-dark)',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'left',
  },
  activityReasoningIcon: {
    fontSize: '10px',
    color: 'var(--info-color)',
  },
  activityReasoningTitle: {
    fontSize: '11px',
  },
  activityViewSwitcher: {
    display: 'flex',
    gap: '4px',
  },
  viewTab: {
    flex: 1,
    padding: '5px 8px',
    border: '1px solid var(--border-subtle)',
    borderRadius: '5px',
    backgroundColor: 'var(--glass-bg-light)',
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  viewTabActive: {
    backgroundColor: 'var(--primary-faint)',
    borderColor: 'var(--primary-border)',
    color: 'var(--primary-color)',
    fontWeight: 700,
  },
  activityFilterBar: {
    padding: '8px 10px',
    borderBottom: '1px solid var(--border-subtle)',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  activitySearch: {
    width: '100%',
    height: '26px',
    padding: '0 8px',
    borderRadius: '5px',
    border: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--glass-bg-light)',
    color: 'var(--text-color)',
    fontSize: '11px',
    outline: 'none',
  },
  filterGroup: {
    display: 'flex',
    gap: '3px',
    flexWrap: 'wrap',
  },
  filterChip: {
    padding: '2px 7px',
    borderRadius: '999px',
    border: '1px solid transparent',
    backgroundColor: 'var(--neutral-faint)',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: '10px',
    fontWeight: 600,
    transition: 'all 0.15s',
  },
  filterChipActive: {
    backgroundColor: 'var(--primary-soft)',
    color: 'var(--primary-color)',
    borderColor: 'var(--primary-border)',
  },
  activityList: {
    padding: '6px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    maxHeight: '400px',
    overflowY: 'auto',
  },

  // Checklist 样式
  activityCheckRow: {
    minWidth: 0,
    flex: 1,
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
  },
  checkMark: {
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 800,
    flexShrink: 0,
    backgroundColor: 'var(--neutral-faint)',
    color: 'var(--text-muted)',
    marginTop: '1px',
  },
  checkMarkDone: {
    backgroundColor: 'var(--success-soft)',
    color: 'var(--success-color)',
  },
  checkMarkFail: {
    backgroundColor: 'var(--error-soft)',
    color: 'var(--error-color)',
  },
  checkMarkWait: {
    backgroundColor: 'var(--info-soft)',
    color: 'var(--info-color)',
    animation: 'pulse 1s infinite',
  },
  activityMainContent: {
    flex: 1,
    minWidth: 0,
  },
  activityTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  activityPhaseChip: {
    flexShrink: 0,
    padding: '1px 5px',
    borderRadius: '4px',
    backgroundColor: 'var(--neutral-faint)',
    color: 'var(--text-dark)',
    fontSize: '10px',
    fontWeight: 700,
  },
  activityDuration: {
    flexShrink: 0,
    fontSize: '10px',
    color: 'var(--text-dark)',
    fontWeight: 600,
    padding: '0 4px',
    borderRadius: '3px',
    backgroundColor: 'var(--neutral-faint)',
  },
  expandDetailButton: {
    border: 'none',
    backgroundColor: 'transparent',
    color: 'var(--text-dark)',
    cursor: 'pointer',
    fontSize: '10px',
    padding: '1px 4px',
    marginTop: '2px',
  },
  activityDetailExpanded: {
    padding: '6px 8px',
    backgroundColor: 'var(--glass-bg-light)',
    borderRadius: '4px',
    margin: '2px 0 4px 26px',
  },
  activityDetailPre: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    fontSize: '11px',
    color: 'var(--text-muted)',
    margin: 0,
    maxHeight: '150px',
    overflowY: 'auto',
  },

  // 通用
  showMoreButton: {
    display: 'block',
    width: '100%',
    padding: '6px',
    border: 'none',
    backgroundColor: 'transparent',
    color: 'var(--primary-color)',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 600,
    textAlign: 'center',
    transition: 'background-color 0.15s',
  },
  emptyTab: {
    padding: '20px 10px',
    textAlign: 'center',
    color: 'var(--text-dark)',
    fontSize: '12px',
  },
};
