export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        setImmediate: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Date: "readonly",
        Intl: "readonly",
        global: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        fetch: "readonly",
        AbortController: "readonly",
        Buffer: "readonly",
        URL: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", {
        "args": "none",
        "caughtErrors": "none",
        "ignoreRestSiblings": true
      }],
      "no-undef": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "warn",
      "no-console": "off",
      "no-constant-condition": "warn",
      "no-redeclare": "error",
      "no-shadow": "off",
      "eqeqeq": "warn",
      "curly": "warn",
      "no-throw-literal": "error",
    },
  },
  {
    // Tests directory: allow more flexibility
    files: ["tests/**/*.{js,mjs}"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        expect: "readonly",
        performance: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
      "no-empty": "off",
      "no-throw-literal": "off",
      "no-undef": "error",
      "no-console": "off",
    },
  },
];
