export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        setImmediate: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Date: "readonly",
        Intl: "readonly",
        global: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        fetch: "readonly",
        AbortController: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "warn",
      "no-console": "off",
      "no-constant-condition": "warn",
      "no-redeclare": "error",
      "no-shadow": "warn",
      "eqeqeq": "warn",
      "curly": "warn",
      "no-throw-literal": "error",
    },
  },
];
