export const PlatformType = {
  CLI: 'cli',
  DESKTOP: 'desktop',
  WEB: 'web',
};

export const RuntimeEvent = {
  AGENT_START: 'agent:start',
  AGENT_STOP: 'agent:stop',
  AGENT_ERROR: 'agent:error',
  AGENT_COMPLETE: 'agent:complete',
  AGENT_STREAM: 'agent:stream',
  AGENT_THINKING: 'agent:thinking',
  AGENT_TEXT_DELTA: 'agent:text_delta',
  AGENT_REASONING_DELTA: 'agent:reasoning_delta',
  AGENT_TOOL_CALL_DELTA: 'agent:tool_call_delta',
  AGENT_INTERACTION_REQUEST: 'agent:interaction_request',
  AGENT_INTERACTION_CANCEL: 'agent:interaction_cancel',
  TOOL_CALL: 'tool:call',
  TOOL_RESULT: 'tool:result',
  TOOL_ERROR: 'tool:error',
  TOOL_ACTIVITY: 'tool:activity',
  TOOL_PROGRESS: 'tool:progress',
  TOOL_LOADED: 'tool:loaded',
  TOOL_UNLOADED: 'tool:unloaded',
  MESSAGE_RECEIVED: 'message:received',
  MESSAGE_SENT: 'message:sent',
  STATUS_UPDATE: 'status:update',
  CONFIG_CHANGE: 'config:change',
  SESSION_CHANGE: 'session:change',
  SUBAGENT_UPDATE: 'subagent:update',
  MEMORY_UPDATE: 'memory:update',
  MEMORY_CLEAR: 'memory:clear',
  PLUGIN_REGISTER: 'plugin:register',
  PLUGIN_UNREGISTER: 'plugin:unregister',
  PLUGIN_ENABLE: 'plugin:enable',
  PLUGIN_DISABLE: 'plugin:disable',
  EXECUTION_PLAN_CREATED: 'plan:created',
  EXECUTION_PLAN_UPDATED: 'plan:updated',
  PLAN_DECOMPOSED: 'plan:decomposed',
  PLAN_EXECUTED: 'plan:executed',
};

export const MAX_ITERATIONS_DEFAULT = 60;
