import { writeFile, mkdir } from 'fs/promises';
import { join, resolve } from 'path';
import { tmpdir } from 'os';
import { ToolCategory } from '../../core/types/index.js';

export default function handoff() {
  return {
    name: 'handoff',
    description:
      'Session continuity document generator. Creates a structured handoff document capturing session progress, decisions, open questions, and next steps. Updates memory manager with session history and saves HANDOFF.md to the OS temp directory, not the workspace.',
    category: ToolCategory.skill_productivity,
    params: {
      session_summary: {
        type: 'string',
        description:
          'Summary of what was accomplished and the current state of work in this session.',
      },
      next_steps: {
        type: 'string',
        description: 'Comma-separated list of next steps to take, ordered by priority.',
      },
      open_questions: {
        type: 'string',
        description: 'Comma-separated list of open questions that need resolution.',
      },
    },
    required: ['session_summary'],
    handler: async (params, ctx) => {
      const { session_summary, next_steps, open_questions } = params;
      const { workingDirectory, memoryManager, sessionManager } = ctx;

      const timestamp = new Date().toISOString();
      const sessionId = sessionManager?.currentSessionId || 'unknown';

      // Parse comma-separated lists
      const stepsList = next_steps
        ? next_steps
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean)
        : [];
      const questionsList = open_questions
        ? open_questions
            .split(',')
            .map((q) => q.trim())
            .filter(Boolean)
        : [];

      // Build handoff document
      const doc = [
        `# Session Handoff`,
        ``,
        `**Session ID:** ${sessionId}`,
        `**Timestamp:** ${timestamp}`,
        ``,
        `---`,
        ``,
        `## Completed Work`,
        ``,
        session_summary,
        ``,
        `## In-Progress Work`,
        ``,
        stepsList.length > 0
          ? stepsList.map((step, i) => `${i + 1}. ${step}`).join('\n')
          : '_No in-progress items recorded._',
        ``,
        `## Key Decisions and Reasons`,
        ``,
        `_Decisions made during this session should be documented here with their rationale._`,
        ``,
        `## Open Questions`,
        ``,
        questionsList.length > 0
          ? questionsList.map((q, i) => `${i + 1}. ${q}`).join('\n')
          : '_No open questions._',
        ``,
        `## Next Steps (by priority)`,
        ``,
        stepsList.length > 0
          ? stepsList.map((step, i) => `- [ ] **P${i + 1}:** ${step}`).join('\n')
          : '_No next steps defined._',
        ``,
        `## Important Context`,
        ``,
        `> **Do not lose this information.** This context is critical for the next session.`,
        ``,
        `- Session was active at: ${timestamp}`,
        `- Working directory: ${workingDirectory}`,
        stepsList.length > 0 ? `- ${stepsList.length} pending action(s) identified` : '',
        questionsList.length > 0 ? `- ${questionsList.length} open question(s) remaining` : '',
        ``,
        `## Related Files`,
        ``,
        `_List of files touched or created during this session should be appended here._`,
        ``,
        `---`,
        ``,
        `*Generated by AI Engineering Mastery Agent - Handoff Tool*`,
      ]
        .filter(Boolean)
        .join('\n');

      // Save HANDOFF.md to OS temp directory so session artifacts do not pollute the repo.
      const handoffDir = resolve(tmpdir(), 'mastery', 'handoffs');
      const handoffPath = join(
        handoffDir,
        `HANDOFF-${sessionId}-${timestamp.replace(/[:.]/g, '-')}.md`,
      );
      await mkdir(handoffDir, { recursive: true });
      await writeFile(handoffPath, doc, 'utf-8');

      // Update memory manager with session history
      if (memoryManager) {
        try {
          await memoryManager.store({
            key: `handoff_${sessionId}`,
            value: {
              sessionId,
              timestamp,
              summary: session_summary,
              nextSteps: stepsList,
              openQuestions: questionsList,
              handoffFile: handoffPath,
            },
          });
        } catch {
          // Memory manager update is best-effort
        }
      }

      return `${doc}\n\n---\n\nSaved handoff file: ${handoffPath}`;
    },
  };
}
