import { writeFile, mkdir } from 'fs/promises';
import { join, resolve } from 'path';
import { ToolCategory } from '../../core/types/index.js';

/**
 * Convert a title string to a URL-safe slug.
 */
function slugify(title) {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export default function to_prd() {
  return {
    name: 'to_prd',
    description:
      'Synthesize conversation context into a Product Requirements Document (PRD). Generates a structured PRD with background, user stories, requirements, acceptance criteria, milestones, and more. Saves to docs/prd/{title-slug}.md.',
    category: ToolCategory.skill_output,
    params: {
      title: {
        type: 'string',
        description: 'Title of the product or feature.',
      },
      context: {
        type: 'string',
        description: 'Conversation context and description of the product/feature to document.',
      },
      format: {
        type: 'string',
        description: 'Output format level of detail.',
        enum: ['detailed', 'concise'],
      },
    },
    required: ['title', 'context'],
    handler: async (params, ctx) => {
      const { title, context, format } = params;
      const { workingDirectory } = ctx;

      const isDetailed = format === 'detailed';
      const slug = slugify(title);
      const timestamp = new Date().toISOString().split('T')[0];

      const doc = [
        `# Product Requirements Document: ${title}`,
        ``,
        `**Date:** ${timestamp}`,
        `**Status:** Draft`,
        ``,
        `---`,
        ``,
        `## 1. Background & Goals`,
        ``,
        context,
        ``,
        `### Goals`,
        ``,
        `- Define the core problem this product/feature addresses`,
        `- Establish measurable success criteria`,
        `- Align stakeholders on scope and priorities`,
        ``,
        `## 2. User Stories`,
        ``,
        `| ID | As a... | I want to... | So that... | Priority |`,
        `|----|---------|-------------|-----------|----------|`,
        `| US-1 | _user_ | _describe the action_ | _describe the value_ | Must |`,
        ``,
        `_Populate user stories based on the conversation context above._`,
        ``,
        `## 3. Requirements`,
        ``,
        `### 3.1 Must Have`,
        ``,
        `- [ ] REQ-1: _Core requirement derived from context_`,
        `- [ ] REQ-2: _Essential functionality_`,
        ``,
        `### 3.2 Should Have`,
        ``,
        `- [ ] REQ-3: _Important but not critical requirement_`,
        `- [ ] REQ-4: _Expected functionality_`,
        ``,
        `### 3.3 Nice to Have`,
        ``,
        `- [ ] REQ-5: _Desirable enhancement_`,
        `- [ ] REQ-6: _Future consideration_`,
        ``,
        `## 4. Non-Functional Requirements`,
        ``,
        isDetailed
          ? [
              `| Category | Requirement | Target |`,
              `|----------|-------------|--------|`,
              `| Performance | Response time | < 200ms |`,
              `| Scalability | Concurrent users | 1000+ |`,
              `| Security | Authentication | OAuth 2.0 / JWT |`,
              `| Reliability | Uptime SLA | 99.9% |`,
              `| Accessibility | WCAG compliance | Level AA |`,
              ``,
            ].join('\n')
          : `- Performance, security, scalability, and reliability requirements TBD`,
        ``,
        `## 5. Acceptance Criteria`,
        ``,
        isDetailed
          ? [
              `### AC-1: Core Functionality`,
              ``,
              `- **Given** _precondition_`,
              `- **When** _action_`,
              `- **Then** _expected result_`,
              ``,
              `### AC-2: Edge Cases`,
              ``,
              `- **Given** _precondition_`,
              `- **When** _action_`,
              `- **Then** _expected result_`,
              ``,
            ].join('\n')
          : [
              `- **Given** _precondition_`,
              `- **When** _action_`,
              `- **Then** _expected result_`,
              ``,
            ].join('\n'),
        `## 6. Out of Scope`,
        ``,
        `- Items explicitly excluded from this release`,
        `- Features deferred to future phases`,
        `- Third-party integrations not yet planned`,
        ``,
        `## 7. Milestones`,
        ``,
        `| Phase | Milestone | Target Date | Deliverables |`,
        `|-------|-----------|-------------|-------------|`,
        `| M1 | Discovery & Planning | _TBD_ | PRD approval, design mockups |`,
        `| M2 | Core Development | _TBD_ | MVP implementation |`,
        `| M3 | Testing & QA | _TBD_ | Test coverage, bug fixes |`,
        `| M4 | Launch | _TBD_ | Production deployment, monitoring |`,
        ``,
        `---`,
        ``,
        `*Generated by AI Engineering Mastery Agent - PRD Tool*`,
      ]
        .filter(Boolean)
        .join('\n');

      // Save to docs/prd/{slug}.md
      const docsDir = resolve(workingDirectory, 'docs', 'prd');
      await mkdir(docsDir, { recursive: true });
      const filePath = join(docsDir, `${slug}.md`);
      await writeFile(filePath, doc, 'utf-8');

      return doc;
    },
  };
}
